<a href="https://colab.research.google.com/github/didiercsgm/THC/blob/main/TareaE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TAREA/EXAMEN 1

FECHA DE ENTREGA: 27 DE OCTUBRE 2023

INTEGRANTES:

Ríos Rocha Miguel Eduardo

Serrano Moreno Didier Camille Gaetan

1. Sumas de matrices rectangulares.

In [13]:
import numpy as np #Definimos np con la blioteca de numpy, como estamos en colab, esto se queda para el resto de las células

dims = (3, 3) #definimos las dimensiones de la matriz, en este caso es 3 por 3

#Pedimos crear los arreglos de una manera aleatoria con números del 1 al 100, con las dimensiones ya definidas
arr1 = np.floor(np.random.rand(*dims)*101)
arr2 = np.floor(np.random.rand(*dims)*101)

#Definimos una función para la suma de matrices
def arr_sum(a = arr1,b = arr2):

#Si las matrices no son de forma nxn no se podran sumar
  if a.shape != b.shape:
    print("no se pueden sumar matrices de diferentes dimensiones entrada a entrada")
    return

#Agregamos otro arreglo el cual se llenara con la suma de matrices, del mismo tamaño a las matroces al ser sumadas
  arr_res = np.zeros(a.shape)

#Pedimos que para cada elemento de la primera matriz se sume con el elemnto en su misma posición de la segunda matriz
  for i in np.ndindex(a.shape):
      arr_res[i] = a[i] + b[i]

#Pedimos que imprima ambas matrices y la suma de las matrices
  print(a)
  print("sumado con")
  print(b)
  print("es")
  print(arr_res)

arr_sum()

[[89. 96. 26.]
 [51. 49. 41.]
 [15. 26.  5.]]
sumado con
[[12. 94. 44.]
 [16. 96. 36.]
 [43. 13. 84.]]
es
[[101. 190.  70.]
 [ 67. 145.  77.]
 [ 58.  39.  89.]]


2. Multiplicación entrada a entrada rectangulares.

In [14]:
dims = (3, 3)

arr1 = np.floor(np.random.rand(*dims)*101)
arr2 = np.floor(np.random.rand(*dims)*101)

#Definimos una función para la multiplicación entrada por entrada
def arr_mult(a = arr1,b = arr2):

#Si las matrices no son de forma nxn no se podran multiplicar
  if a.shape != b.shape:
    print("no se pueden multiplicar matrices de diferentes dimensiones entrada a entrada")
    return

  arr_res = np.zeros(a.shape)

#Pedimos que para cada elemento de la primera matriz se multiplique por el elemnto en su misma posición de la segunda matriz
  for i in np.ndindex(a.shape):
      arr_res[i] = a[i] * b[i]

#Pedimos que imprima ambas matrices aleatorias con el producto entrada por entrada
  print(a)
  print("multiplicado por")
  print(b)
  print("entrada a entrada es")
  print(arr_res)

arr_mult()

[[39. 58. 15.]
 [32. 93. 78.]
 [88. 46. 34.]]
multiplicado por
[[46. 38. 52.]
 [73. 82. 13.]
 [43. 32. 77.]]
entrada a entrada es
[[1794. 2204.  780.]
 [2336. 7626. 1014.]
 [3784. 1472. 2618.]]


3. La traza.

In [15]:
dims = (3, 3)

arr1 = np.floor(np.random.rand(*dims)*101)


#Definimos una función para la traza de una matriz
def arr_trace(a = arr1):

#Si la matriz no es de forma nxn no se podra hacer la traza
  if len(a) != len(a[1]):
    print("la traza sólo existe para matrices cuadradas")
    return

  arr_res = 0 #Nueva variable igual a cero, se le van a ir sumando los resultados parciales

#Pedimos que para cada elemento n de la fila n del arreglo se sume con arr_res
  for i in range(len(a)):
    arr_res += a[i,i]

#Pedimos que imprima la matriz aleatoria con el resultado de la traza
  print("la traza de")
  print(a)
  print("es",arr_res)

arr_trace()

la traza de
[[62. 61. 14.]
 [17.  3. 57.]
 [35.  9. 37.]]
es 102.0


4. La transpuesta.

In [16]:
dims = (3, 3)

arr1 = np.floor(np.random.rand(*dims)*101)

#Definimos una función para la transpuesta de una matriz
def arr_transpose(a = arr1):

#Damos las filas y las columnas de la matriz original
	fils = len(a)
	cols = len(a[0])

 #Pedimos un nuevo arreglo con las las filas del tamaño de las columnas de la primera matriz y columnas de tamaño de las filas
	arr_res = np.zeros((cols,fils))

 #Pedimos que se impriman el número de columnas y filas de la matriz resultante
	print("El número de columnas y filas son", fils, "y", cols)

#Pedimos que para cada elemento de las columnas y filas se intercambien en el nuevo arreglo las columnas con las filas y las filas con las columnas
	for i in range(cols):
		for j in range(fils):
			arr_res[i,j] = a[j,i]

#Pedimos que imprima la matriz original y el resultado de la transpuesta
	print("la transpuesta de")
	print(a)
	print("es\n", arr_res)

arr_transpose()

El número de columnas y filas son 3 y 3
la transpuesta de
[[28. 64. 49.]
 [96. 96. 14.]
 [66. 68. 77.]]
es
 [[28. 96. 66.]
 [64. 96. 68.]
 [49. 14. 77.]]


5. El máximo y mínimo elemento en una matriz.

In [10]:
dims = (3,3)

arr1 = np.floor(np.random.rand(*dims)*101)


#definimos función para sacar los máximos y mínimos
def arr_maxmin(a = arr1):

  print("la matriz es",a)

  n = a.size # definimos una variable como los elementos en una dada fila de a
  swap = True # definimos una variable con valor de verdad para el bucle
  #empezamos el bucle, que va a ordenar a los elementos de la matriz
  while swap:
    swap = False # decimos que el bucle tiene que seguir al principio
    for i in range(n - 1):  # bucles for anidados para ir comparando dos dados elementos de la matriz
      for j in range(n - i - 1):
        if a.flat[j] > a.flat[j + 1]: # comparamos los dos dados elmentos de la matriz
          a.flat[j], a.flat[j + 1] = a.flat[j + 1], a.flat[j] # si la comparación resulta verdadera, cambiamos el orden

  max = a[len(a)-1,len(a[0])-1]
  min = a[0,0]

  print("el valor máximo es", max)
  print("el vamor mínimo es", min)

arr_maxmin()

la matriz es [[66. 11.  0.]
 [77. 45. 77.]
 [54. 77. 75.]]
el valor máximo es 77.0
el vamor mínimo es 0.0


6. La suma del cuadrado de los elementos de una matriz.

In [17]:
dims = (3, 3)

arr1 = np.floor(np.random.rand(*dims)*101)

#Definimos una función para la suma del cuadrado de los elementos de una matriz
def arr_squaresum(a = arr1):

#Creamos una variable igual a 0
  arr_res = 0

#Pedimos que para cada elemento del primer arreglo se eleve al cuadrado y luego que se sume con la variable arr_res
  for i in np.ndindex(a.shape):
     arr_res += a[i] ** 2

#Pedimos que imprima la matriz aleatoria con el resultado de la suma del cuadrado de los elementos de una matriz
  print("la suma de los cuadrados de los elementos de")
  print(a)
  print("es", arr_res)

arr_squaresum()

la suma de los cuadrados de los elementos de
[[ 41.  73. 100.]
 [ 40.  19.   4.]
 [  9.  55.  23.]]
es 22622.0


7. La potencia de matrices.




In [18]:
shape = (3, 3)

arr1 = np.floor(np.random.rand(*shape)*101)
#Definimos una función para la potencia de matrices
def arr_power(a = arr1, p = 3):

#Se pide un número para potenciar la matriz
  p = float(input("a qué potencia deseas elevar la matriz "))

#Pedimos un nuevo arreglo que se llene con las potencias de la matriz anterior
  arr_res = np.zeros(a.shape)

#Pedimos que para cada elemento de la primera matriz se elve al número dado
  for i in np.ndindex(a.shape):
      arr_res[i] = a[i] ** p
#Pedimos que imprima la matriz y la potencia de la matriz
  print("la potencia de")
  print(a)
  print("a la",p,"es")
  print(arr_res)

arr_power()

a qué potencia deseas elevar la matriz 3
la potencia de
[[25. 86. 73.]
 [80. 29. 32.]
 [48. 28. 98.]]
a la 3.0 es
[[ 15625. 636056. 389017.]
 [512000.  24389.  32768.]
 [110592.  21952. 941192.]]
